# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ember-api

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/main_ember-api.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: api/package-lock.json

      - name: install
        working-directory: api
        run: npm ci

      - name: build (optional)
        working-directory: api
        run: npm run build --if-present

      - name: test (optional)
        working-directory: api
        run: npm run test --if-present

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-app
          path: api

      - name: login to azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_298408D4FB304F60B9F4AEC3C47B750A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D3D77769A6BA4D048343E3649FDF9157 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_92204967630B4F8DBB48662DA954AF63 }}

      - name: deploy to azure web app
        uses: azure/webapps-deploy@v3
        with:
          app-name: ember-api
          slot-name: Production
          package: api
